version: '3.8'

services:
  persistence-postgres:
    image: postgres:14.1-alpine
    restart: unless-stopped
    volumes:
      - persistence-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
volumes:
  persistence-postgres-data: